baseUrl = "http://blog.soulshake.net/"
CanonifyUrls = true
languageCode = "en-us"
title = "a flash of light and a distant boom"

[params]
	description = "There be mraagons"
    Author = "AJ Bowen"
    disqusShortname = "blogsoulshakenet"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"

[indexes]
  tag = "tags"
  topic = "topics"
