baseUrl = "http://blog.soulshake.net/"
CanonifyUrls = true
languageCode = "en-us"
title = "a flash of light and a distant boom."

[params]
	description = "There be mraagons"
    Author = "AJ Bowen"
    disqusShortname = "blogsoulshakenet"

