hugo:
  #image: soulshake/blog.soulshake.net:latest
  build: .
  container_name: blog.soulshake.net
  volumes:
    - ./src/:/src
    - ./output/:/output
    - ./log/hugo.log:/hugo.log
  restart: always
  expose:
    - "80"
  ports:
    - '80:80'
  extra_hosts:
    - "blog.soulshake.net:localhost"
  entrypoint:
    - hugo
    - server
    - --verbose
    - --ignoreCache
    - --source=/src
    - --destination=/output
    - --watch=true
    - --config=/src/config.toml
    - --theme=blackburn
    - --baseUrl=blog.soulshake.net
    - --bind=0.0.0.0
    - --port=80
  working_dir: /src
